version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:00"
          timezone: "Europe/London"
      open-pull-requests-limit: 10
      assignees:
          - "seanbuckle"
      labels:
          - "dependencies"
          - "automated"
      commit-message:
          prefix: "chore"
          include: "scope"
      groups:
          development-dependencies:
              dependency-type: "development"
          production-dependencies:
              dependency-type: "production"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:00"
          timezone: "Europe/London"
      open-pull-requests-limit: 5
      assignees:
          - "seanbuckle"
      labels:
          - "dependencies"
          - "github-actions"
          - "automated"
          - "security"
      commit-message:
          prefix: "chore"
          include: "scope"
