feat:
    - branch: ["feat/**"]
fix:
    - branch: ["fix/**"]
refactor:
    - branch: ["refactor/**"]
chore:
    - branch: ["chore/**", "dependabot/**"]
test:
    - branch: ["test/**"]

docs:
    - branch: ["docs/**"]
    - changed-files:
          - any-glob-to-any-file: ["README.md", "docs/**", "LICENSE"]

security:
    - branch: ["security/**", "patch/**"]
    - changed-files:
          - any-glob-to-any-file: [".github/workflows/**", "auth/**"]

"priority: high":
    - branch: ["hotfix/**", ".*-urgent$"]

breaking-change:
    - branch: ["break/**", ".*-major$"]

in-progress:
    - branch: ["wip/**"]

on-hold:
    - branch: ["hold/**", "draft/**"]
