name: "Auto Labeller"
on:
    pull_request_target:

jobs:
    triage:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            # 1. We must check out the PR branch code so the labeler can find the config file
            - uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            # 2. Run the labeler now that the files are present locally
            - uses: actions/labeler@v6
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  configuration-path: .github/labeler.yml
                  sync-labels: true
